const bible_jevangelski_podiji = [
  { id: 1, category: '', subcategories: [
    { id: 1, event: 'Пролог', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Родовід Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Благовістя Захарії про народження Іоанна Предтечі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Благовіщення Пресвятої Богородиці Діва Марія в домі Єлизавети', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Народження Іоанна Предтечі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Одкровення Йосифу Праведному про Боговтілення', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Різдво Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Поклоніння пастирів', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Обрізання і наречення імя Ісус', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Стрітення Господа в храмі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Поклоніння волхвів', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 12, event: 'Втеча до Єгипту', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 13, event: 'Винищення немовлят у Віфліємі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 14, event: 'Повернення з Єгипта, оселення в Назареті, отрок Ісус у храмі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 15, event: 'Проповідь Іонна Предтечі в пустині, свідчення про Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 16, event: 'Хрещення Господнє', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 17, event: 'Спокушання Ісуса Христа в пустині', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 2, category: 'Діла Господа Ісуса Христа в Іудеї після спокушання Його в пустині до першої Пасхи', subcategories: [
    { id: 1, event: 'Наступні свідчення Іоанна Предтечі про Ісуса Христа, перші ученики Господа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 3, category: 'Діла Господа Ісуса Христа в Галілеї після повернення з Іудеї', subcategories: [
    { id: 1, event: 'Чудо в Кані галілейській', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Відвідування Капернауму', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 4, category: 'Події в Іудеї', subcategories: [
    { id: 1, event: 'Вигнання торгуючих з храму Свідчення Ісуса Христа про Своє Богосинівство', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Бесіда Ісуса Христа з Никодимом', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Ісус з учениками в Іудеї Останнє свідчення Іоанна Хрестителя про Ісуса Христа перед учениками', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Увязнення Іоанна Предтечі в темницю', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 5, category: 'Події на шляху з Іудеї в Галілею', subcategories: [
    { id: 1, event: 'Повернення до Галілеї Бесіда з самарянкою', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]}
  ]},

  { id: 6, category: 'Служіння Ісуса Христа в Галілеї', subcategories: [
    { id: 1, event: 'Прихід Ісуса Христа в Кану Галілейську; зцілення сина капернаумського царедворця', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Початок євангельської проповіді', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Проповідь Ісуса Христа в назаретській синагозі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Оселення і проповідь у Капернаумі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Покликання до апостольства Петра, Андрея, Якова і Іоанна', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Зцілення біснуватого в капернаумській синагозі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Зцілення тещі Симона', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Зцілення багатьох хворих', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Благовістя в Галілеї', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Зцілення прокаженого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 12, event: 'Зцілення розслабленого в Капернаумі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 13, event: 'Покликання Левія-Матфея до апостольства', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 14, event: 'Відповідь ученикам Іоанна про піст', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 7, category: 'Події в Іудеї', subcategories: [
    { id: 1, event: 'Ісус Христос в Єрусалимі на другій Пасці', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Одкровення Ісуса Христа про Своє Богосинівство', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 8, category: 'Проповідь і чудеса Ісуса Христа в Галілеї', subcategories: [
    { id: 1, event: 'Про значення суботи; зривання колосків', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Зцілення сухорукого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Злоба фарисеїв і прагнення народу до Ісуса', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Обрання 12 апостолів', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Нагірна проповідь', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Зцілення слуги капернаумського сотника', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Воскрешення сина вдови в Наїні', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Свідчення Ісуса про Себе і про Іоанна Хрестителя перед Іоанновими учениками', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Покликання струджених і обтяжених', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Прощення грішниці в домі фарисея Симона', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Зцілення біснуватого глухонімого сліпого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 12, event: 'Викривання хули на Духа Святого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 13, event: 'Про вимогу знамення', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 14, event: 'Про внутрішнє світло', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 15, event: 'Похвала слухаючим слово Боже', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 16, event: 'Викривання зовнішньої праведності', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 17, event: 'Вчення біля моря притчами про Царство Боже', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 18, event: 'Про слідування за Ісусом', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 19, event: 'Приборкання бурі на шляху через Геннісаретське озеро в Гадаринську країну', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 20, event: 'Зцілення біснуватих у Гадаринській країні', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Воскрешення дочки Іаіра, зцілення кровоточивої хворої', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 22, event: 'Зцілення двох сліпих', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 23, event: 'Зцілення біснуватого німого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 24, event: 'Проповідь в назаретській синагозі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 25, event: 'Проповідь у навколишніх містах і селищах', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 26, event: 'Повчання 12 при посиланні їх на проповідь', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 27, event: 'Смерть Іоанна Хрестителя', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 28, event: 'Чутка про Ісуса Христа, сумяття Ірода', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 29, event: 'Повернення 12 з проповіді', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 30, event: 'Насичення 5000 народу пятьма хлібами і двома рибами', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 31, event: 'Прямування Ісуса Христа до учеників по воді', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 32, event: 'Зцілення хворих в Генісаретській країні', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                 { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 33, event: 'Бесіда Ісуса Христа про небесний хліб', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 9, category: 'Події від третьої пасхи до четвертої - пасхи страждань', subcategories: [
    { id: 1, event: 'Викриття іудеїв у лицемірному виконанні заповідей', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Подорож Ісуса Христа в межі Тира і Сидона, зцілення дочки хананеянки', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Зцілення глухонімого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Зцілення безлічі народу біля Генісаретського озера', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Насичення 4000 сімома хлібами і кількома рибами', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Прибуття в країну Магдалинську. Відповідь фарисеям, що просили знамення з неба', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Застереження учеників від закваски фарисейської', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Зцілення сліпого у Віфсаїді', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Сповідування Петра у Кесарії Филиповій', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Перше провіщення Ісуса Христа про хресні страждання; повчання про несення хреста', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Преображення Господнє', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 12, event: 'Друге провіщення Ісуса Христа про хресні страждання', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 13, event: 'Зцілення біснуватого лунатика', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 14, event: 'Третє провіщення Ісуса Христа про хресні страждання', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 15, event: 'Останнє перебування Господа Ісуса Христа в Капернаумі; відповідь Ісуса Христа про податок на храм', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 16, event: 'Повчання про смирення', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 17, event: 'Промова про спасіння пропащих, притча про заблудлу вівцю', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 18, event: 'Вчення про прощення гріха ближнього', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 10, category: 'Господь Ісус Христос у Галілеї перед празником Кущей', subcategories: [
    { id: 1, event: 'Відмова Ісуса Христа йти на празник до Єрусалима', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Подорож Ісуса Христа до Єрусалима', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Неприязне ставлення до Ісуса Христа самаринців', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Відповідь Господа Ісуса Христа тим, що побажали йти за ним', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Послання 70 на проповідь; докір містам, які не прийняли проповіді', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Заклик струджених і обьяжених', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Питання законника про вічне життя і про ближнього і притча про милосердного самарянина', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Ісус Христос в домі Марфи і Марії', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Вчення Ісуса Христа про молитву', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Ісус на обіді у фарисея, викривання законників', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Повчання про правила життя Христовим послідовником', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 11, category: 'Ісус Христос в Єрусалимі на празнику Кущей', subcategories: [
    { id: 1, event: 'Спір у народі про Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Про жінку, взяту в перелюбстві', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Викривання іудеїв при скарбниці храму', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Зцілення сліпонародженого', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: '"Пастир добрий"', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Звістка про галілеян, побитих Пілатом, наставлення про покаяння', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Притча про безплідну смоковницю', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Зцілення в синагозі в суботу жінки, скорченої 18 років', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Вчення Ісуса Христа про Царство Боже в притчах', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Бесіда Ісуса Христа на празнику Оновлення притворі Соломоновому', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Віддалення Господа Ісуса Христа з Єрусалима в зайорданську країну Перею', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 12, category: 'Вчення Господа Ісуса Христа по дорозі назад в Єрусалим із зайорданської країни', subcategories: [
    { id: 1, event: 'Промова Ісуса Христа про число тих, що спасаються', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Провіщення про страждання в Єрусалимі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Ісус Христос на обіді у фарисея; зцілення хворого на водянку; притча про покликаних на вечерю', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Самозречення послідовників Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Притчі про заблудлу вівцю, загублену драхму і блудного сина', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Про невірного домоправителя', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Викривання фарисеїв; притча про багача і Лазаря', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Наставляння ученикам про виконання обовязку', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Зцілення десяти прокажених', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Відповідь про друге пришестя', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Притча про несправедливого суддю', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 12, event: 'Притча про митаря і фарисея', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 13, event: 'Вчення про шлюб', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 14, event: 'Благословення дітей', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 15, event: 'Відповідь багатому юнакові', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 16, event: 'Питання Петра про нагороду послідовникам Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 17, event: 'Притча про найнятих у виноградник робітниках', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 18, event: 'Воскрешення Лазаря', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 19, event: 'Змова начальників іудейських проти Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 20, event: 'Провіщення Ісуса Христа про хресне страждання на шляху до Єрусалима', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Прохання синів Зеведеєвих про місце в Царстві Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Ісус Христос в Ієрихоні; зцілення сліпих', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Навернення Закхея', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Притча про того, що пішов на війну і про тих, які примножили таланти', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Ісус Христос у Віфанії', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 21, event: 'Вхід Господній в Єрусалим; зцілення хворих в Єрусалимі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 13, category: 'Великий понеділок', subcategories: [
    { id: 1, event: 'Безплідна смоковниця', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Вигнання торгуючих храму', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 14, category: 'Великий вівторок', subcategories: [
    { id: 1, event: 'Викривання начальників іудейських і повчання Господа в храмі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Про жертву бідної вдовиці', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Промова Ісуса Христа перед еллінами та іудеями', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Пророцтва і притчі Ісуса Христа про Єрусалим і про друге пришестя', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 15, category: 'Велика середа', subcategories: [
    { id: 1, event: 'Ісус Христос у Віфанії', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Змова іудеїв, зрада Іуди', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 16, category: 'Великий четвер', subcategories: [
    { id: 1, event: 'Пасхальна вечеря', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Моління про чашу', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 17, category: 'Велика пятниця', subcategories: [
    { id: 1, event: 'Взяття Ісуса Христа під варту', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Допит Ісуса Христа у Анни', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Суд Синедріону над Ісусом Христом у Канафи', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Зречення Петра', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Вирок Синедріону', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Кінець Іуди', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Ісус Христос у Пілата', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Хресний шлях і Голгофа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Погребіння Ісуса Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},

  { id: 18, category: 'Воскресення Ісуса Христа. Ранок Воскресення', subcategories: [
    { id: 1, event: 'Пізно в суботу Марія Магдалина з другою Марією йдуть дивитися гроб', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 2, event: 'Марія Магдалина та інші жінки купують аромати, щоб ранком помазати Ісуса', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 3, event: 'Землетрус; ангел відвалює камінь від печери', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 4, event: 'Марія Магдалина поспішає до гробу. Побачивши, що він пустий, вона повертається до Петра і Іоанна', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 5, event: 'Прихід до гробу до схід сонця групи галілейських жон-мироносиць; явлення їм ангелів', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 6, event: 'Петро та Іоанн з Марією Магдалиною прибігають до порожнього гробу', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 7, event: 'Явлення Воскреслого Христа Марії Магдалині', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 8, event: 'Прихід на гроб при сході сонця другої групи жонмироносець; явлення їм ангела', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 9, event: 'Повернення мироносиць від гробу; явлення їм воскреслого Христа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 10, event: 'Повідомлення учеників про Воскресення Господа галілейських жон-мироносиць', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 11, event: 'Повідомлення учеників про Воскресення Господа Марією Магдалиною', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 12, event: 'Явлення Ісуса Христа еммауським подорожнім', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 13, event: 'Явлення Ісуса Христа в перший день тижня ученикам без Фоми', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 14, event: 'Явлення Ісуса Христа як минуло вісім днів', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 15, event: 'Явлення Ісуса Христа біля моря Тіверіалського', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 16, event: 'Явлення Ісуса Христа на горі', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
    { id: 17, event: 'Вознесіння Господа', items: [{ id: 1, label_uk: '', label_chapter: '' }, { id: 2, label_uk: '', label_chapter: '' },
                                { id: 3, label_uk: '', label_chapter: '' }, { id: 4, label_uk: '', label_chapter: '' },
    ]},
  ]},
]

export default bible_jevangelski_podiji;
